### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/article_presets#1]
TBD

**Comment by gharlan** [comment]
Ich würde es jedenfalls anders nennen. Denn du meinst ja Slices und nicht Module. 
Als ich zunächst das neue Repo gesehen hab, dachte ich, es ginge um die Installation von Modulen, automatisch während der Addon-Installation oder so.

**Comment by schuer** [comment]
Ich würde es auch anders nennen. Es geht ja um eine Inhaltsstruktur, die beim Anlegen von Artikeln automatisch angelegt wird. Also sowas wie
- Prepare Content base
- Prepare Content structure
- Prepare Article
- Prepare New Articles
- Frau Schultze

**Comment by phoebusryan** [comment]
@gharlan Da hast du natürlich recht. Es war einfach das was mir grade im Kopf rumschwirrte. Aber es ist natürlich verkehrt.

@schuer Stimmt. Irgendwas beschreibendes wäre toll. Frau Müller oder so. 💃 

Auto-Add-Slices-On-New-Article -> AASONA 👍

**Comment by schuer** [comment]
Article Presets
Article Templates

**Comment by schuer** [comment]
Mit der Art der Implementierung, wie du sie in #2 beschrieben hast, würde meiner Meinung nach jetzt folgendes perfekt passen:

**Article Templates**

Nicht?

**Comment by phoebusryan** [comment]
Hmm.. es geht so. Es wird ja kein Template kopiert. Der Name könnte deshalb verwirrend sein weil es ja auch Templates gibt in Redaxo. Ich fände Article Presets daher besser.

**Comment by gharlan** [comment]
> Der Name könnte deshalb verwirrend sein weil es ja auch Templates gibt in Redaxo.

Ja, das finde ich auch. Wäre besser, wenn man ohne das Wort "Template" auskommt.

**Comment by schuer** [comment]
Okay, stimmt. Na dann vielleicht wirklich Article Presets.

**Comment by schuer** [comment]
@phoebusryan Habe auf Kleinschreibung und Unterstrich statt Bindestrich geändert, sonst gibt es Probleme mit myREDAXO.
