### ISSUE TITLE
Blöcke werden nicht kopiert

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/article_presets#14]
Aktuelle Version 1.1
Ich erhalte zwar eine Kopie der Metadaten im neuen Artikel. Aber die Blöcke nicht.

**Comment by shauste** [comment]
Selbes Phänomen hier, die Blöcke werden nicht übernommen.

**Comment by phoebusryan** [comment]
Was habt ihr für eine Redaxoversion?

**Comment by AWqxKAWERbXo** [comment]
Ist Blöcks im Einsatz?

**Comment by skerbis** [comment]
REDAXO 5.5.1 , nein Blöcks ist nicht im Einsatz

**Comment by phoebusryan** [comment]
Verrückt. Bei mir funktioniert das. Könnt ihr mal die Config und ein Beispiel posten? Als Screenshot oder ähnliches. Gerne auch direkt in Slack.

**Comment by skerbis** [comment]
Ich habe soeben einen Test in einer Demo durchgeführt. Hier funktioniert es perfekt. Auch habe ich Blöcks und sogar history hier installiert. Es muss wohl an einem anderen AddOn liegen.

**Comment by phoebusryan** [comment]
Gut zu wissen. Dann beisst sich das wohl irgendwie. Was hast du bei der anderen Installation drin?

@shauste Was hast du für Addons drin?

**Comment by skerbis** [comment]
Ich glaube es was mit Structure_Tweaks zu tun. Nachdem ich dieses  jetzt neu installiert habe, ist das Problem weg.

**Comment by phoebusryan** [comment]
Okay, dann schliesse ich hier mal. Sonst einfach wieder öffnen.
