### ISSUE TITLE
Diskussion: Wie implementieren?

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/article_presets#2]
Hi zusammen,
ich muss/soll/darf demnächst ein weiteres Redaxo 5 Addon für einen Kunden bauen und werde es wohl so allgemein lösen, dass man es danach der Öffentlichkeit anbieten kann.

Es geht darum, dass wenn man einen Artikel anlegt im Backend, automatisch auch einige Module (Slices!) angelegt werden. Sprich es gibt die Module A, B, C, D und E und wenn ich einen Artikel hinzufüge, werden automatisch einige Blöcke mit den Modulen angelegt. Natürlich sind die Formulare dann leer.

Schön wäre es, wenn es irgendwie flexibel wäre. Ich stelle mir das Ähnlich wie bei meinen Editoren. Quasi ein Profil anlegen und dann sagen, welche Module hinzugefügt werden.. Dies anhand zwei Möglichkeiten:
1. Wenn ein Artikel ein bestimmtes Template hat
2. Wenn ein Artikel zu einer bestimmten Kategorie gehört.

Was meint ihr?

**Comment by gharlan** [comment]
Idee: Über eine Art Template-Artikel realisieren. Zum Beispiel: Wenn es ein (Offline-)Artikel mit dem Namen "_template" in einer Kategorie gibt, dann wird der jeweils als Basis für neue Artikel verwendet.
So könnte man die Slices auch mit Values vorbelegen, auch Mehrsprachigkeit wäre direkt mit abgedeckt.

**Comment by phoebusryan** [comment]
Ich finde deinen Vorschlag gut, Gregor und werde es wohl so umsetzen im ersten Schritt. Andere Ideen kann ich ja jederzeit noch einbauen.

**Comment by skerbis** [comment]
Finde auch dass es eine gute Idee ist. So können die Module auch vorbefüllt sein und der Redakteur weiß sofort was er damit machen kann. 
Ist aus meiner Sicht auch die beste Lösung mit jedem Modul kompatibel zu sein. 
Ohne die Template-Artikel hat man evtl. Probleme mit Blöcken, die bestimmte Valiues ausgefüllt haben müssen, damit sie funktionieren.

**Comment by phoebusryan** [comment]
Also ich habs nun zusammen. Ich würde ein Addon bauen, wo man PRO Kategorie einen Artikel als Vorlage definieren kann z.b. anhand einer Selectbox. Wenn dann ein neuer Artikel in der Kategorie angelegt wird, wird der Inhalt des Vorlagen-Artikels kopiert. Evtl. wärs sogar schöner komplett den Artikel zu kopieren anstelle eines neuen zu erstellen, da man dann auch Metadaten vordefinieren könnte.

Die Vorlagen-Artikel würde ich dann Mithilfe eines regulären Ausdruckes in der boot.php des Addons bearbeiten, damit sie nicht gelöscht werden können. Simpel aber effizienz.
