### ISSUE TITLE
Warnung vor Änderung eines Startartikels möglich?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/article_presets#5]
Evtl. wäre noch sinnvoll, dass jemand eine Warnung erhält, wenn er vorhat in einer Kategorie, die mit Article_Presets verknüpft ist den Startartikel zu ändern.

**Comment by phoebusryan** [comment]
Ich denke, das ist nicht mehr nötig - ich habe es gerade auf einen Kategorie-Select umgebaut.

**Comment by skerbis** [comment]
hm .... wird die Kategorie nicht über die ID des Startartikels referenziert? Ich meine schon.  ID von Startartikel und ID von Kategorie sind glaube ich gleich.

**Comment by tbaddade** [comment]
> ID von Startartikel und ID von Kategorie sind glaube ich gleich.

nicht nur gleich sondern es ist dieselbe Id. Es gibt keine Kategorien im Sinne von "Ordner", es gibt nur Artikel und davon werde einige als Kategorien dargestellt.

**Comment by skerbis** [comment]
Darauf wollte ich hinweisen. Wenn also jemand da was ändert stimmt ja die Zuordnung in article_presets nicht mehr.

**Comment by phoebusryan** [comment]
Ich weiss was du meinst. Hm. Eine Warnung würde gehen. Schöner wäre wohl das Updaten des Artikels in der Konfiguration via EP. Sofern das möglich ist.

**Comment by phoebusryan** [comment]
@skerbis Ist das überhaupt noch relevant? Ich habe das Issue gerade nochmal durchgelesen und verstehe das Problem wohl nicht mehr 💃

**Comment by skerbis** [comment]
Habe mich jetzt länger nicht mit dem Addon beschäftigt. Ich melde mich.

**Comment by skerbis** [comment]
Ja das ist noch relevant. Da die Kategorie-ID=Startartikel-ID der Kategorie, wird die Einstellung in article_presets ungültig, wenn der Redakteur einen Artikel zum neuen Startartikel der Kategorie macht. Der Redakteur sollte eine Warnung erhalten, dass eine Änderung des Startartikels Konsequenzen hat.
