### ISSUE TITLE
Vorschau und Auswahl beim Anlegen eines Artikels

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/article_presets#9]
gesehen bei notion.so :
![image](https://cloud.githubusercontent.com/assets/688274/26037061/a1bb88a8-38eb-11e7-8ad9-d62090dc724d.png)

Wäre gleichzeitig die Idee, dass man mehrere Presets pro Kategorie anbieten kann.

**Comment by phoebusryan** [comment]
Ansich eine gute Idee aber relativ aufwendig so umzusetzen, stelle ich mir.

PR willkommen :)

**Comment by skerbis** [comment]
Aufgrund keiner Aktivität - close
